name: Checkov

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform,cloudformation,kubernetes,dockerfile,github_actions
          output_format: cli,sarif
          output_file_path: checkov-results.sarif
          skip_check: | # A long TODO list
            CKV_AWS_22  # Ensure ALB is configured with access logs
            CKV_AWS_131  # Ensure that ALB drops HTTP headers
            CKV_AWS_150  # Ensure that Load Balancer has deletion protection enabled
            CKV_AWS_261  # Ensure HTTP HTTPS Target group defines Healthcheck
            CKV_AWS_338  # Ensure CloudWatch log groups retains logs for at least 1 year
            CKV_AWS_158  # Ensure that CloudWatch Log Group is encrypted by KMS
            CKV_AWS_161  # Ensure RDS database has IAM authentication enabled
            CKV_AWS_157  # Ensure that RDS instances have Multi-AZ enabled
            CKV_AWS_118  # Ensure that enhanced monitoring is enabled for Amazon RDS instances
            CKV_AWS_353  # Ensure that RDS instances have performance insights enabled
            CKV_AWS_354  # Ensure RDS Performance Insights are encrypted using KMS CMKs
            CKV_AWS_226  # Ensure DB instance gets all minor upgrades automatically
            CKV_AWS_129  # Ensure that respective logs of Amazon Relational Database Service (Amazon RDS) are enabled
            CKV_AWS_293  # Ensure that AWS database instances have deletion protection enabled
            CKV_AWS_136  # Ensure that ECR repositories are encrypted using KMS
            CKV_AWS_51   # Ensure ECR Image Tags are immutable
            CKV_AWS_65   # Ensure container insights are enabled on ECS cluster
            CKV_AWS_249  # Ensure that the Execution Role ARN and the Task Role ARN are different in ECS Task definitions
            CKV_AWS_290  # Ensure IAM policies does not allow write access without constraints
            CKV_AWS_355  # Ensure no IAM policies documents allow "*" as a statement's resource for restrictable actions
            CKV_AWS_7    # Ensure rotation for customer created CMKs is enabled
            CKV_AWS_149  # Ensure that Secrets Manager secret is encrypted using KMS CMK
            CKV_AWS_23   # Ensure every security group and rule has a description
            CKV_AWS_130  # Ensure VPC subnets do not assign public IP by default
            CKV2_AWS_57  # Ensure Secrets Manager secrets should have automatic rotation enabled
            CKV2_AWS_11  # Ensure VPC flow logging is enabled in all VPCs
            CKV2_AWS_30  # Ensure Postgres RDS as aws_db_instance has Query Logging enabled
            CKV2_AWS_12  # Ensure the default security group of every VPC restricts all traffic
            CKV2_AWS_64  # Ensure KMS key Policy is defined
            CKV2_AWS_60  # Ensure RDS instance with copy tags to snapshots is enabled
            CKV2_AWS_28  # Ensure public facing ALB are protected by WAF
            CKV_AWS_103  # Ensure that load balancer is using at least TLS 1.2
            CKV2_AWS_3   # Ensure GuardDuty is enabled to specific org/region
            CKV_DOCKER_2 # Ensure that HEALTHCHECK instructions have been added to container images
            CKV_GHA_8    # Ensure that private access Personal Access Tokens (PATs) are not used in workflows
            CKV_GHA_9    # Ensure that private access Personal Access Tokens (PATs) are not used in workflows

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: checkov-results.sarif
